---

distribution_python_cryptography:
  CentOS: python2-cryptography
  Ubuntu: python3-cryptography

code_server_version: "{{ role_vars.code_server_version | default(None) }}"
code_server_tag_name: "{{ role_vars.code_server_tag_name | default(code_server_version) }}"

code_server_port: 8998

code_server_base_extensions:
  - auchenberg.vscode-browser-preview

code_server_extensions: "{{ role_vars.code_server_extensions | default([]) | union(code_server_base_extensions) | list }}"
