---

training_folder: /training

training_vars_file: "{{ training_folder }}/training.yml"
trainer_vars_file: "{{ training_folder }}/trainer.yml"

current_session_folder: "{{ training_folder }}/sessions/current"
current_session_vars_folder: "{{ current_session_folder }}/group_vars/all"
current_session_local_ip: "{{ lookup('pipe', 'wget -qO- ifconfig.me') }}"
current_session_authorized_ips: "{{ authorized_ips | default([]) | union([current_session_local_ip]) | list | sort }}"

aws_account_id: '682417792030'
aws_region: eu-west-3
aws_ses_region: eu-west-1
aws_password: zenika

users: "{{ ['trainer'] | union(trainees | default({}) | map(attribute='username') | list ) }}"

base_open_ports:
  - 22
  - 80
  - 443
  - from: 8000
    to: 8999
