---

- name: Restart tomcat service
  service:
    name: "{{ distribution_tomcat[ansible_facts.distribution] }}"
    state: restarted
  listen:
    - Restart tomcat

- name: Restart guacd service
  service:
    name: guacd
    state: restarted
  listen:
    - Restart guacd
