---

training_name: test

#aws_region: eu-west-3
aws_instances:
  - name: node0
    type: t2.micro
  - name: node1
    type: t2.micro
  - name: node2
    type: t2.micro

roles:
  - name: code-server
    target:
      - node0
  - name: workspaces
    target:
      - node0
  - name: docker
    target:
      - node0
    vars:
      docker_version: 19.03
  - name: kubernetes
    target:
      - node0
    vars:
      kubernetes_version: 1.18
      install_kubeadm: True
      install_minikube: True

tools:
  - git
