---

training_name: test

#aws_region: eu-west-3
aws_instances:
  - name: node0
    type: t2.micro
  - name: node1
    type: t2.micro
  - name: node2
    type: t2.micro
#os: ubuntu

roles:
  - name: guacamole
    target:
      - node0
  - name: code-server
    target:
      - node0
  - name: workspaces
    target:
      - node0
  - name: docker
    target:
      - node0
    vars:
      docker_version: 19.03  # or '5:19.03' for Ubuntu
      install_compose: True
  - name: kubernetes
    target:
      - node0
    vars:
      kubernetes_version: 1.19
      install_kubeadm: True
      install_minikube: True
      install_kubelet: True

tools:
  - git
