---

common_base_tools:
  - vim
  - unzip
  - bash-completion
  - jq

distribution_base_tools:
  CentOS:
    - nc
  Ubuntu:
    - netcat

base_tools: "{{ common_base_tools | union(distribution_base_tools[ansible_facts.distribution] | default([])) }}"
