---

- name: Install EPEL repos
  yum:
    name: epel-release

- name: Install base tools
  yum:
    name: "{{ base_tools | union(tools | default([])) }}"

- name: Add /usr/local/bin in sudo PATH
  lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults *secure_path'
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'

- name: Add LF at end of curl output
  become: no
  lineinfile:
    path: ~/.curlrc
    line: '--write-out "\n"'
    create: yes
