---

- name: Setup Google Chrome repo
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    enabled: true
  when: ansible_facts.distribution == 'CentOS'

- block:

    - name: Add Google repo key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub

    - name: Add Google Chrome repo
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome

  when: ansible_facts.distribution == 'Ubuntu'

- name: Install Chrome
  package:
    name: google-chrome-stable

- name: Compute latest version
  block:
    - name: Get releases
      uri:
        url: https://api.github.com/repos/cdr/code-server/releases
      register: code_server_releases
    - name: Compute latest usable version
      set_fact:
        code_server_version: "{{ (code_server_releases.json | to_json | from_json | json_query(query)).name }}"
      vars:
        query: "[?starts_with(name, 'v')] | [0]"
  when: not code_server_version

- name: Clean version
  set_fact:
    code_server_version: "{{ code_server_version | regex_replace('^v', '') }}"

- name: Check minimal version
  assert:
    that: code_server_version is version('3.2', '>=')
    msg: code-server version must be >= 3.2.0

- name: "Extract code-server {{ code_server_version }}"
  unarchive:
    src: "https://github.com/cdr/code-server/releases/download/v{{ code_server_version }}/code-server-{{ code_server_version }}-linux-amd64.tar.gz"
    remote_src: yes
    dest: /usr/local/lib
    extra_opts:
      - --transform
      - "s/-{{ code_server_version }}-linux-amd64//"
    creates: /usr/local/lib/code-server/code-server

- name: Link code-server binary
  file:
    src: /usr/local/lib/code-server/bin/code-server
    dest: /usr/local/bin/code-server
    state: link

- name: Create code-server config folder
  file:
    path: "~{{ current_os.user }}/.config/code-server"
    state: directory
    owner: "{{ current_os.user }}"
    group: "{{ current_os.user }}"
    mode: 0755

- name: Create code-server config
  template:
    src: config.yaml
    dest: "~{{ current_os.user }}/.config/code-server/config.yaml"
    owner: "{{ current_os.user }}"
    group: "{{ current_os.user }}"
    mode: 0644
  notify:
    - Restart code-server

- name: Install openssl dependency
  package:
    name: "{{ distribution_python_cryptography[ansible_facts.distribution] }}"
    state: present

- name: Generate code-server key
  openssl_privatekey:
    path: "~{{ current_os.user }}/.config/code-server/code-server.key"
    mode: 0400
  become: no
  notify:
    - Restart code-server

- name: Generate code-server CSR
  openssl_csr:
    path: "~{{ current_os.user }}/.config/code-server/code-server.csr"
    privatekey_path: "~{{ current_os.user }}/.config/code-server/code-server.key"
    common_name: "{{ public_dns_name }}"
    subject_alt_name:
      - "DNS:{{ public_dns_name }}"
      - "IP:{{ ansible_host }}"
  become: no

- name: Generate code-server certificate
  openssl_certificate:
    path: "~{{ current_os.user }}/.config/code-server/code-server.crt"
    csr_path: "~{{ current_os.user }}/.config/code-server/code-server.csr"
    privatekey_path: "~{{ current_os.user }}/.config/code-server/code-server.key"
    selfsigned_not_after: +5d
    provider: selfsigned
  become: no
  notify:
    - Restart code-server

- name: Install code-server service
  template:
    src: code-server.service
    dest: /usr/lib/systemd/system/code-server.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart code-server

- name: Flush handlers
  meta: flush_handlers

- name: Launch and enable code-server service
  service:
    name: code-server
    state: started
    enabled: true

- name: Install extensions
  command: |
    code-server --install-extension {{ item }}
  environment:
    SERVICE_URL: https://marketplace.visualstudio.com/_apis/public/gallery
    NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-bundle.crt
  become: no
  register: this
  changed_when: "'is already installed' not in this.stdout"
  loop: "{{ code_server_extensions }}"
